{{- if and .Values.istio.enabled .Values.istio.authz.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-wallet-only
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "muffin-currency.name" . }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.istio.authz.allowFromServiceAccount }}
{{- end }}

