{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "muffin-currency.serviceAccountName" . }}
  labels:
    app: {{ include "muffin-currency.name" . }}
{{- end }}

