replicaCount: 2

image:
  repository: aadan1lov/muffin-wallet
  tag: "1.1.0"
  pullPolicy: Always

containerPort: 8081

serviceAccount:
  create: true
  name: muffin-wallet

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: muffin-wallet.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

istio:
  enabled: true
  ingress:
    enabled: true
    host: wallet.example.com
    gateway:
      name: muffin-wallet-gateway
      selector:
        istio: ingressgateway
      port: 80
  mtls:
    enabled: true
  resilience:
    currency:
      timeout: 2s
      retries:
        attempts: 3
        perTryTimeout: 1s
        retryOn: 5xx,connect-failure,refused-stream,reset
  serviceEntry:
    postgres:
      enabled: true
      host: host.docker.internal
      port: 5432

env:
  JDK_JAVA_OPTIONS: -Dspring.config.additional-location=/app/config/application.yaml

applicationConfig:
  server:
    port: 8081
  spring:
    datasource:
      url: jdbc:postgresql://host.docker.internal:5432/muffin_wallet
      username: muffin-wallet
  currencyService:
    url: http://muffin-currency:8083/rate

secret:
  SPRING_DATASOURCE_PASSWORD: muffin-wallet

migrations:
  enabled: true
  image:
    repository: aubhon/muffin-wallet-migrations
    tag: "1.0.0"
  dbTag: "1.0.0"

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 50
    periodSeconds: 10
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 50
    periodSeconds: 10
