{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "muffin-wallet.serviceAccountName" . }}
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
{{- end }}

